# Generated by Django 4.2.5 on 2023-12-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturamodel',
            name='tiempo',
            field=models.FloatField(default=0.0),
        ),
    ]
